version: '3'
services:
  db:
    container_name: db
    image: postgres:10.1-alpine
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - data-redis:/data
  web:
    container_name: web
    build: .
    image: web
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && rake db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/myapp:rw
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    stdin_open: true
    tty: true
  sidekiq:
    image: web
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - web
      - redis
      - db
    stdin_open: true
    tty: true
volumes:
  data-postgres:
    driver: local
  data-redis:
    driver: local
