- name: stop project
  shell: docker-compose stop
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: cleanup
  shell: docker-compose rm -f -v
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: build and start project
  shell: docker-compose up --build -d
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}
