- name: stop project
  shell: docker-compose stop
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: cleanup
  shell: docker-compose rm -f -v
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: build project
  shell: docker-compose build
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: prepare assets and db
  shell: docker-compose run --rm web rake assets:precompile && rake db:migrate
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: stop project
  shell: docker-compose stop
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}

- name: start project
  shell: docker-compose up -d
  register: ps
  args:
    chdir: backend/current/deploy/production
- debug: msg={{ ps.stdout }}
