version: '3'
services:
  db:
    container_name: db
    image: postgres:10.1-alpine
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
  web:
    container_name: web
    build:
      context: ../../
      dockerfile: deploy/production/Dockerfile
    command: bash -c "rake assets:precompile db:migrate && rails s -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ../../.env
volumes:
  data-postgres:
    driver: local
