---
- name: production deploy
  hosts: production
  remote_user: app
  vars:
    ansistrano_deploy_to: "/home/app/backend"
    ansistrano_version_dir: "releases"
    ansistrano_current_dir: "current"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: "git"
    ansistrano_allow_anonymous_stats: false
    ansistrano_git_repo: "git@github.com:EugeneTymoshenko/margatsni.git"
    ansistrano_git_branch: "deployment"
    ansistrano_git_identity_key_remote_path: "/home/app/.ssh/id_rsa"
    ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/after-deploy.yml"
    ansistrano_shared_files: ".env"

    ansible_user: "app"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_host: "3.122.69.171"
    ansible_port: "8888"
  roles:
    - role: ansistrano.deploy
